name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        name: Lint Commit Messages